server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-products
          uri: http://localhost:8082/api/
          predicates:
            - Path=/api/**
        - id: ms-notification
          uri: http://localhost:8083/
          predicates:
            - Path=/api/**
        - id: ms-authorization
          uri: http://localhost:8084/
          predicates:
            - Path=/api/**

logging:
  level:
    web: debug