server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: api-products
  datasource:
    url: jdbc:mysql//localhost:3306/challenge
    username: root
    password: root
  jpa:
    open-in-view: true

logging:
  level:
    web: debug