server:
  port: 8084
  servlet:
    context-path: /api

spring:
  application:
    name: ms-authorization
  datasource:
    url: jdbc:mysql//localhost:3306/challenge
    username: root
    password: root
  jpa:
    open-in-view: true
  security:
    user:
      name: user
      password: 123456

logging:
  level:
    web: debug